name: Android CI

on:
  push:
    branches: [ "main", "master", "stable" ]
  pull_request:
    branches: [ "main", "master", "stable" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean project
        run: ./gradlew clean

      # 🔥 Construye los flavors que realmente existen
      - name: Build Normal Release APK
        run: ./gradlew assembleNormalRelease --no-daemon

      - name: Build Fdroid Release APK
        run: ./gradlew assembleFdroidRelease --no-daemon

      # 🚀 Sube cualquier APK generado sin importar flavor
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: BoomingMusic-release
          path: app/build/outputs/apk/**/*.apk
